image: alpine/edge
secrets:
  - 3a2b6687-249f-4db0-a816-7d7d88caecf2
  - e137f559-6a19-4c76-b50b-91a295047540
sources:
  - git@git.sr.ht:~patrickhaussmann/rna
tasks:
  - mirror: |
      curl -LsS "https://raw.githubusercontent.com/PatrickHaussmann/dotfiles/5f20648c7a246f79a4f5f6923e8eeaa15897173f/.ssh/known_hosts_fixed" >> ~/.ssh/known_hosts
      echo -e "Host github.com\n    IdentityFile ~/.ssh/e137f559-6a19-4c76-b50b-91a295047540\n    IdentitiesOnly yes\n    BatchMode yes\n" >> ~/.ssh/config
      cd rna/
      git push git@github.com:app-5ls-de/rna.git
